# https://render.com/docs/blueprint-spec
services:
  - type: web
    name: grt-pit-ui
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "20"
